# Программирование Python

## "Обработка многомерных массивов в библиотеке NumPy с использованием IPython"

Выполнил студент Левицкий Андрей Александрович группы ИС-м19-1.

### Интерпретатор IPython и оболочка Jupyter

Интерпретатор **IPython** является полезным интерактивным интерфейсом для языка Python и предоставляет некоторые удобные инструменты для отладки, анализа процесса выполнения программ на языке Python.

**Jupyter** - веб-оболочка для интерпретатора IPython, позволяющая объединить код, текст, формулы и диаграммы в единый документ (*блокнот Jupyter*) и распространять их для других пользователей.

Пример работы с разметкой среды Jupyter можно посмотреть в этом блокноте и в [блокноте с разнообразными примерами использования символов и тегов разметки](https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)

Для быстрого доступа к документации и другой соответствующей информации в IPython используется знак `?`. Например справку по команде `len` можно поучить так:

In [ ]:
?len

Такой подход можно применять к любым функциям и методам в IPython.

In [ ]:
L = [1,2,3]
L.insert?

#### "Магические" команды IPython
"Магические" команды позволяют организовывать выполнение подпрограмм в среде IPython, а также их профилирование, отладку и другие операиции, не связанные непосредственно с языком Python. Например, кманда `%run <скрипт>` запускает в интерактивной оболочке IPython скрипт на Python, а `%timeit`автоматически определяет время выполнения следующего за ней однострочного оператора. Эта команда будет выполнять множественные запуски с целью получения максимально надежных результатов. 

In [ ]:
%timeit L = [n ** 2 for n in range(1000)]

Справку по магическим функциям можно получить при помощи знака `?`. Например:

In [ ]:
%timeit?

Для доступа к общему описанию доступных «магических» функций введите команду:

In [ ]:
%magic

Для быстрого получения простого списка всех доступных «магических» функций:

In [ ]:
%lsmagic

С помощью «магической» функции %xmode (сокращение от exception mode — режим отображения исключений) мы можем управлять тем, какая информация будет выведена.
Функция %xmode принимает на входе один аргумент, режим, для которого есть три значения: Plain (Простой), Context (По контексту) и Verbose (Расширенный).

#### Отладка и профилирование.

Отладчик в оболочке IPython называется ipdb (сокращение от IPython Debugger — «отладчик IPython»).

Интерфейс для отладки в IPython — «магическая» команда `%debug`. Если ее вызвать после столкновения с исключением, она автоматически откроет интерактивную командную строку откладки в точке возникновения исключения. Командная строка ipdb позволяет изучать текущее состояние стека, доступные переменные и даже выполнять команды Python.
Для подробной информации воспользуйтесь командой help в отладчике или загляните в [онлайн-документацию по ipdb](https://github.com/gotcha/ipdb)

Оболочка IPython предоставляет широкий выбор функциональности для выполнения подобного мониторинга скорости выполнения кода и его профилирования. Для этого применяются следующие "магческие команды":

* `%time` — длительность выполнения отдельного оператора;
* `%timeit` — длительность выполнения отдельного оператора при неоднократном повторе, для большей точности;
* `%prun` — выполнение кода с использованием профилировщика;
* `%lprun` — пошаговое выполнение кода с применением профилировщика;
* `%memit` — оценка использования оперативной памяти для отдельного оператора;
* `%mprun` — пошаговое выполнение кода с применением профилировщика памяти.


Пример работы команды `%timeit` рассмотрен выше. Он позволяет оценивать время выполнения однострочных инструкций, выполняя многократный их запуск.

In [ ]:
%timeit sum(range(100))

Если же нужно оценить время, которое затрачивается на выполнение нескольких строк кода, нужно использовать команду с двумя знаками `%` - `%%timeit`:

In [ ]:
%%timeit
    total = 0
    for i in range(1000):
        for j in range(1000):
            total += i * (-1) ** j

Для некоторых фрагментов кода будет полезно оценивать их длительность работы только по одному запуску. Для этого можно применять команду `%time` или `%%time` для многострочного фрагмента:

In [ ]:
%%time
    total = 0
    for i in range(1000):
        for j in range(1000):
            total += i * (-1) ** j

Программы состоят из множества отдельных операторов, и иногда оценка времени их выполнения в контексте важнее, чем по отдельности. В языке Python имеется встроенный профилировщик кода (о котором можно прочитать в документации 
языка Python), но оболочка IPython предоставляет намного более удобный способ его использования в виде «магической» функции `%prun`. Для пошагового профилирования может использоваться функция `%lprun`. Аналогично для профилирования объема используемой оперативной памяти могут применяться команды  `%memit` и `%mprun`. Подробную информацию  них можно узнать воспользовавшись справкой по этим командам.

### Основы Python

Данный блокнот представляет собой адаптированную версию блокнота http://cs231n.github.io/python-numpy-tutorial.

#### Введение

Python - отличный язык программирования общего назначения, а с помощью нескольких популярных библиотек (numpy, scipy, matplotlib) он становится мощной средой для научных вычислений.

Мы ожидаем, что у многих из вас уже есть некоторый опыт работы с Python и numpy; для остальных вас этот раздел будет служить быстрым курсом знакомства как с языком программирования Python, так и использования Python для научных вычислений.

Кто-то из вас знаком с Matlab, и в этом случае мы также рекомендуем страницу numpy для пользователей Matlab (https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html ).

Будут рассмотрены:
* Основы языка Python: основные типы данных (контейнеры, списки, словари, наборы, кортежи), функции, классы
* Библиотека Numpy: массивы, индексирование массивов, типы данных, математика массивов, трансляция

#### Основы языка Python

Python - высокоуровневый, динамически типизированный язык программирования. Код Python часто называют псевдокодом, поскольку он позволяет вам выражать мощные алгоритмы в нескольких строках кода, оставаясь очень читабельным. В качестве примера рассмотрим реализацию классического алгоритма быстрой сортировки в Python:

In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

#### Версии Python

В настоящее время существуют две поддерживаемых версии Python - 2.7 и 3.6. В Python 3.0 добавлено много обратно несовместимых изменений, поэтому код, написанный для версии 2.7, может не работать под 3.6 и наоборот. Для этого класса весь код будет использовать Python 3.6.

Вы можете проверить свою версию Python в командной строке, запустив `python -V`.

#### Основные типы данных

##### Числа

Целые числа и числа с плавающей запятой работают так, как и в других языках:

In [ ]:
x = 3
print(x, type(x))

In [ ]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;

In [ ]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

In [ ]:
y = 2.5
print(type(y)) # Prints "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

Обратите внимание: в отличие от многих языков Python не имеет унарных инкрементов (x++) или декрементов (x--).
Python также имеет встроенные типы для длинных целых чисел и комплексных чисел.

##### Логические переменные

Python реализует все обычные операторы для булевой логики, но использует английские слова, а не символы (`&&`, `||` и т. д.):

In [ ]:
t, f = True, False
print(type(t)) # Prints "<type 'bool'>"

Теперь давайте посмотрим на операции:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

##### Строки

In [ ]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, len(hello))

In [ ]:
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

In [ ]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

Строковые объекты имеют множество полезных методов; например:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Вы можете найти список всех строковых методов в [документации](https://docs.python.org/3/library/stdtypes.html#string-methods).

#### Контейнеры

Python включает несколько встроенных типов контейнеров: списки, словари, множества и кортежи.

##### Списки

Список представляет собой эквивалент массива в Python, но может изменять размер и может содержать элементы разных типов:

In [ ]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs) 

Как обычно, вы можете найти все подробные сведения о списках в [документации](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists).

##### Срезы

Помимо доступа к элементам списка по одному, Python обеспечивает краткий синтаксис для доступа к подспискам; это называется срезами:

In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

##### Циклы

Вы можете перебирать элементы списка следующим образом:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

Если вы хотите получить доступ к индексу каждого элемента в теле цикла, используйте встроенную функцию `enumerate`:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

##### Списковое включение

При программировании часто мы хотим преобразовать один тип данных в другой. В качестве простого примера рассмотрим следующий код, который вычисляет квадрат чисел:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

Вы можете сделать этот код проще, используя включение списка:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

В списковом включении могут также содержаться условия:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

##### Словари

Словарь хранит пары (ключ, значение), похожие на `Map` в Java или `object` в Javascript. Вы можете использовать его следующим образом:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

In [ ]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

In [ ]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

Вы можете найти все, что вам нужно знать о словарях в [документации](https://docs.python.org/3/library/stdtypes.html#dict).


Легко перебирать ключи в словаре:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

Если вы хотите получить доступ к ключам и их соответствующим значениям, используйте метод items:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

Словарные включения: они похожи на списковые включения, но позволяют легко создавать словари. Например:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

##### Множества

Множество представляет собой неупорядоченный набор отдельных элементов. В качестве простого примера рассмотрим следующее:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


In [ ]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))       

_Циклы_: Итерация по множеству имеет тот же синтаксис, что и итерация по списку; однако, поскольку множества неупорядочены, вы не можете знать о порядке, в котором вы выбираете элементы набора:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

Включения множества. Подобно спискам и словарям, мы можем легко создавать меножества с использованием влючения множества:

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

##### Кортежи

Кортеж представляет собой упорядоченный список значений. Кортеж во многом похож на список; одним из наиболее важных различий является то, что кортежи могут использоваться как ключи в словарях и как элементы множеств, в то время как списки не могут. Вот простой пример:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])       
print(d[(1, 2)])

In [ ]:
t[0] = 1

#### Функции

Функции Python определяются с помощью ключевого слова `def`. Например:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

Мы часто будем определять функции с необязательными аргументами, например:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob')
hello('Fred', loud=True)

#### Классы


Синтаксис для определения классов в Python прост:

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

##### <font color='red'>Задание</font>

Создать класс, реализующий функционал учета рейтинга студентов **StudentsRaiting**. Класс должен иметь конструктор, который будет принимать список студентов с результатами сданных экзаменов, реализованый в виде словаря с ключем "ФИО студента" и оценками по экзаменам по 4 предметам (Программирование, Дискретная математика, Иностранный язык, Философия), представленными в виде упорядоченного множества (кортежа). Например:

`{"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)}`

Релизовать методы: 
- добавления студента с оценками по экзаменам
- удаления студента из рейтинга 
- получения списка студентов с рейтингом выше порогового
- метод демонстрации работы методов класса с выводом результатов на печать в виде текстовой таблицы.

Примечание:
Рейтинг составляется по суммарному баллу по всем предметам.

In [ ]:
class StudentsRating:
    def __init__(self, studentsToGrade):
        self.studentsToGrade = studentsToGrade

    def __add__(self, other):
        self.studentsToGrade.update(other)
        return self

    def __sub__(self, other):
        self.studentsToGrade.pop(other, None)
        return self

    def get_greater_than(self, treshold):
        return [student for student, grades in self.studentsToGrade.items() if sum(grades) > treshold]

    def __str__(self):
        return ''.join([student.ljust(30) + ' '.join(list(map(str, grades))) + '\n' for student, grades in self.studentsToGrade.items()])


print("Таблица студентов:")
students = {"Иванов Петр Николавич": (3, 3, 5, 4), "Петров Иван Константинович": (5, 4, 5, 4)}
sr = StudentsRating(students)
print(sr)

print("Добавление нового студента:")
sr += {"Сидоров Емельян Егорович": (4, 3, 4, 5)}
print(sr)

print("Вывод списка студентов с рейтингом выше чем пороговый:")
print(sr.get_greater_than(15))
print()

print("Удаление студента:")
sr -= "Иванов Петр Николавич"
print(sr)


### Numpy

Numpy - это основная библиотека для научных вычислений на Python. Он предоставляет высокопроизводительный объект многомерных массивов и инструменты для работы с этими массивами. Если вы уже знакомы с MATLAB, то можно ознакомиться с эти [материалом](http://wiki.scipy.org/NumPy_for_Matlab_Users), полезным для начала работы с Numpy.

Чтобы использовать Numpy, сначала нужно импортировать пакет `numpy`:

In [ ]:
import numpy as np

#### Массивы

Массив numpy представляет собой сетку значений одного типа и индексируется кортежем неотрицательных целых чисел. Число измерений - это ранг массива; форма массива представляет собой набор целых чисел, дающий размер массива вдоль каждого измерения.

Мы можем инициализировать массивы numpy из списков Python и обращаться к элементам с использованием квадратных скобок:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
print(b.shape)                   
print(b[0, 0], b[0, 1], b[1, 0])

Numpy также предоставляет множество функций для создания массивов:


In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c) 

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

#### Типы данных

Каждый массив numpy представляет собой набор элементов одного типа. Numpy предоставляет большой набор числовых типов данных, которые можно использовать для построения массивов. Numpy пытается угадать тип данных при создании массива, но функции, которые строят массивы, обычно также включают необязательный аргумент, чтобы явно указать тип данных. Например:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

Вы можете прочитать все о типах данных numpy в [документации](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

#### Атрибуты массивов

При работе с массивами библиотеки NumPy можно получить полезную информацию о форме, размерностях массива, о типах данных элементов и занимаемом объеме данных.

In [ ]:
import numpy as np
np.random.seed(0)  # начальное значение для целей воспроизводимости
x1 = np.random.randint(10, size=6)          # одномерный массив
x2 = np.random.randint(10, size=(3, 4))     # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5))  # трехмерный массив

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

In [ ]:
print("dtype:", x3.dtype)

In [ ]:
print("itemsize:", x3.itemsize, "bytes")

In [ ]:
 print("nbytes:", x3.nbytes, "bytes")

##### <font color=red>Задание</font>
Создать массив значений типа `int32` размером 10х10, состоящий из равномерно распределенных случайных чисел от 0 до 100. Получить 4 копии этого массива со значениями типа `uint32`,`int64`,`uint64`,`float`. Для каждого массива вывести сведения: число размерностей, форма, размер, тип данных, размер каждого значения в байтах и размер всего массива в байтах.


In [ ]:
# Выполнение задания
import numpy as np

np.random.seed(0)
matrixInt32 = np.array(np.random.randint(100, size=(10, 10)), dtype=np.int32)
matrixUint32 = np.copy(matrixInt32).astype(dtype=np.uint32)
matrixInt64 = np.copy(matrixInt32).astype(dtype=np.int64)
matrixUint64 = np.copy(matrixInt32).astype(dtype=np.uint64)
matrixFloat = np.copy(matrixInt32).astype(dtype=np.float)

print("matrixInt32:")
print("ndim: ", matrixInt32.ndim)
print("shape:", matrixInt32.shape)
print("size: ", matrixInt32.size)
print("dtype:", matrixInt32.dtype)
print("itemsize:", matrixInt32.itemsize, "bytes")
print("nbytes:", matrixInt32.nbytes, "bytes")
print()

print("matrixUint32:")
print("ndim: ", matrixUint32.ndim)
print("shape:", matrixUint32.shape)
print("size: ", matrixUint32.size)
print("dtype:", matrixUint32.dtype)
print("itemsize:", matrixUint32.itemsize, "bytes")
print("nbytes:", matrixUint32.nbytes, "bytes")
print()

print("matrixInt64:")
print("ndim: ", matrixInt64.ndim)
print("shape:", matrixInt64.shape)
print("size: ", matrixInt64.size)
print("dtype:", matrixInt64.dtype)
print("itemsize:", matrixInt64.itemsize, "bytes")
print("nbytes:", matrixInt64.nbytes, "bytes")
print()

print("matrixUint64:")
print("ndim: ", matrixUint64.ndim)
print("shape:", matrixUint64.shape)
print("size: ", matrixUint64.size)
print("dtype:", matrixUint64.dtype)
print("itemsize:", matrixUint64.itemsize, "bytes")
print("nbytes:", matrixUint64.nbytes, "bytes")
print()

print("matrixFloat:")
print("ndim: ", matrixFloat.ndim)
print("shape:", matrixFloat.shape)
print("size: ", matrixFloat.size)
print("dtype:", matrixFloat.dtype)
print("itemsize:", matrixFloat.itemsize, "bytes")
print("nbytes:", matrixFloat.nbytes, "bytes")

#### Индексация массивов

Numpy предлагает несколько способов индексации в массивах.

**Срезы**: Подобно спискам Python, с массивами numpy можно выполнять срезы. Поскольку массивы могут быть многомерными, вы должны указать срез для каждого измерения массива:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

Срез массива является представлением исходных данных, поэтому его изменение изменит исходный массив.

In [ ]:
print(a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 


Вы также можете комбинировать индексирование целыми числами с индексацией срезами. Однако при этом будет получен массив меньшего ранга, чем исходный массив. Обратите внимание, что это сильно отличается от того, как MATLAB обрабатывает срез массива:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

Два способа доступа к данным в средней строке массива.
Смешивание целых индексов с индексацией срезами дает массив более низкого ранга,
в то время как использование только срезов дает массив того же ранга, что и
исходный массив:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

##### <font color=red>Задание</font>
Выполнить следующий код и объяснить результат.

In [ ]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

*Написать обьяснение:*
Выбирается второй столбец двумерной матрицы. col_r1 содержит одномерный массив, так как для среза был передан целочисленный аргумент. col_r2 содержит двумерный подмассив исходного массива, так как для среза был передан срез

**Целочисленное индексирование массива**: при индексировании в массивах numpy с использованием срезов результирующее представление массива всегда будет подмассивом исходного массива. 
Напротив, индексирование целыми числами позволяет создавать произвольные массивы с использованием данных из другого массива. Например:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

Один полезный трюк с индексированием целочисленного массива - это выбор или изменение одного элемента из каждой строки матрицы:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

Иногда при индексации при помощи срезов бывает полезно работать не с представлением исходного массива, а иметь новый независимый массив данных из исходного массива. Т.е. нужно скопировать представление массива при помощи метода `copy`.

In [ ]:
x = np.random.randint(10,size=(3,4))
x_sub_copy = x[:2, :2].copy()
print(x_sub_copy)

**Индексирование при помощи булевых массивов**: индексирование при помощи булевых массивов позволяет выбирать произвольные элементы массива. Часто этот тип индексации используется для выбора элементов массива, которые удовлетворяют некоторому условию. Вот пример:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

##### <font color=red>Задание</font>
Создать массив случайных целочисленных значений (от -100 до 100) размером 8x8. Используя индексацию булевыми массивами получить:
1. Все элементы, значения которых являются четными числами. Вывести их маску в массиве.
2. Все элементы, значения которых попадают в диапазон от 10 до 50. Вывести их маску в массиве.
3. Все элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50. Вывести их маску в массиве.
4. Все элементы, значения которых являются нечетными числами и модуль значения которых из диапазона от 10 до 50. Вывести их маску в массиве.
5. Все элементы, значения которых являются нечетными числами или отрицательными.

In [ ]:
# Выполнение задания
import numpy as np

np.random.seed(0)
matrix = np.array(np.random.randint(-100, 100, size=(8, 8)))
print("Матрица:")
print(matrix)
print()

print("Четные:")
bool_idx_even = (matrix % 2 == 0)
print(bool_idx_even)
print()

print("В диапазоне от 10 до 50:")
bool_idx_range = (matrix >= 10) & (matrix <= 50)
print(bool_idx_range)
print()

print("Четные и в диапазоне от 10 до 50:")
print(bool_idx_even & bool_idx_range)
print()

print("Нечетные и модуль в диапазоне от 10 до 50:")
bool_idx_uneven_absrange = (matrix % 2 != 0) & (np.absolute(matrix) >= 10) & (np.absolute(matrix) <= 50)
print(bool_idx_uneven_absrange)
print()

print("Нечетные или отрицательные:")
bool_idx_uneven_neg = (matrix % 2 != 0) | (matrix < 0)
print(bool_idx_uneven_neg)
print()


Для краткости мы пропустили много деталей о индексации массива numpy; если вы хотите узнать больше, прочитайте документацию.

#### Изменение формы массивов

Часто требуется изменить форму массива (количество размерностей и их емкость), не изменяя самих элементов массива. Для этого используется специальный метод `reshape`.

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

Другой часто используемый паттерн изменения формы — преобразование одномерного массива в двумерную матрицу-строку или матрицу-столбец. Для этого можно применить метод reshape, но лучше воспользоваться ключевым словом newaxis при выполнении операции среза:

In [ ]:
x = np.array([1, 2, 3]) 
# Преобразование в вектор-строку с помощью reshape
x.reshape((1, 3))

In [ ]:
# Преобразование в вектор-строку посредством newaxis
x[np.newaxis, :]

In [ ]:
# Преобразование в вектор-столбец с помощью reshape
x.reshape((3, 1))

In [ ]:
# Преобразование в вектор-столбец посредством newaxis
x[:, np.newaxis]

#### Объединение массивов

Для работы с массивами с различающимися измерениями удобно использовать функции `np.vstack` (вертикальное объединение) и `np.hstack` (горизонтальное объединение):


In [ ]:
 x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])
# Объединяет массивы по вертикали
np.vstack([x, grid])

In [ ]:
# Объединяет массивы по горизонтали
y = np.array([[99],[99]])
np.hstack([grid, y])


Функция `np.dstack` аналогично объединяет массивы по третьей оси.

#### Разбиение массивов
Противоположностью слияния является разбиение, выполняемое с помощью функций np.split, np.hsplit и np.vsplit. Каждой из них необходимо передавать список индексов, задающих точки раздела:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

Функции `np.hsplit` и `np.vsplit` действуют аналогично:

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
upper, lower = np.vsplit(grid, 2)
print(upper)
print(lower)

In [ ]:
left, right = np.hsplit(grid, 2)
print(left)
print(right)

##### <font color=red>Задание</font>
Написать функцию, которая из исходного массива размером 8х8 получает (при помощи операций разбиения и объединения) массив, в котором переставлены квадранты 1-й с 3-м, 2-й с 4-м по сравнению с исходным массивом. Продемонстрировать работу функции все шаги алгоритма сопроводить подробными комментариями и отладочным выводом промежуточных результатов.

Т.е. например из массива

`[[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]`
 
должен получиться массив 

 `[[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]`

In [ ]:
# Выполнение задания
import numpy as np

np.random.seed(0)
matrix = np.array(np.random.randint(-100, 100, size=(8, 8)))
print("Исходная матрица:")
print(matrix)
print()

# 1 2 -> 3 4
# 4 3 -> 2 1

quadrant_1 = np.vsplit(np.hsplit(matrix, 2)[0], 2)[0]
quadrant_2 = np.vsplit(np.hsplit(matrix, 2)[1], 2)[0]
quadrant_3 = np.vsplit(np.hsplit(matrix, 2)[1], 2)[1]
quadrant_4 = np.vsplit(np.hsplit(matrix, 2)[0], 2)[1]

quadrant_34 = np.hstack([quadrant_3, quadrant_4])
quadrant_21 = np.hstack([quadrant_2, quadrant_1])
newMatrix = np.vstack([quadrant_34, quadrant_21])

print("Преобразованная матрица:")
print(newMatrix)
print()


#### Вычисления с массивами

Основные математические функции работают поэлементно с массивами и доступны как в виде перегрузок операторов, так и как функций в модуле numpy:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Обратите внимание, что в отличие от MATLAB, * является поэлементным умножением, а не матричным умножением. Вместо этого мы используем функцию точки для вычисления скалярных произведений векторов, умножения вектора на матрицу и умножения матриц. точка доступна как функция в модуле numpy, так и как метод экземпляра объектов массива:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

Numpy предоставляет множество полезных функций для выполнения вычислений с массивами; одна из самых полезных - это `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

Полный список математических функций, предоставляемых numpy, содержится в [документации](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Помимо вычисления математических функций с использованием массивов, нам часто приходится изменять форму масива или иным образом манипулировать данными в массивах. Простейшим примером такой операции является транспонирование матрицы; для транспонирования матрицы просто используйте атрибут T объекта массива:

In [ ]:
print(x)
print(x.T)

In [ ]:
v = np.array([1,2,3])
print(v) 
print(v.T)

#### Трансляция

Трансляция - мощный механизм, позволяющий numpy работать с массивами разных форм при выполнении арифметических операций. Часто мы имеем меньший массив и больший массив, и мы хотим использовать меньший массив несколько раз, чтобы выполнить некоторую операцию над большим массивом.

Например, предположим, что мы хотим добавить постоянный вектор в каждую строку матрицы. Мы могли бы сделать это следующим образом:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

Это работает; однако, когда матрица x очень велика, вычисление явного цикла в Python может быть медленным. Заметим, что добавление вектора v в каждую строку матрицы x эквивалентно формированию матрицы vv путем стыковки нескольких копий v по вертикали, а затем выполнения поэлементного суммирования x и vv. Мы могли бы реализовать этот подход следующим образом:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Трансляция позволяет нам выполнять это вычисление без фактического создания нескольких копий v. Рассмотрим этот вариант, использующий трансляцию:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

Строка `y = x + v` работает, даже если` x` имеет форму `(4, 3)` и `v` имеет форму` (3,) `из-за широковещания; эта строка работает так, как если бы v фактически имела форму `(4, 3)`, где каждая строка была копией `v`, а сумма выполнялась поэлементно.

**Трансляция** двух массивов выполняется в соответствии с правилами:

1. Если массивы не одного ранга, к форме массива меньшего ранга добавляется одно измерение слева до тех пор, пока формы массивов не будут иметь одинаковую длину.
2. Два массива, как говорят, совместимы в некотором измерении, если они имеют одинаковый размер в этом измерении, или если один из массивов имеет размер 1 в этом измерении.
3. Массивы могут транслироваться друг с другом, если они совместимы во всех измерениях.
4. После трансляции каждый массив ведет себя так, как если бы он имел форму, равную поэлементному максимуму форм двух входных массивов.
5. В любом измерении, где один массив имел размер 1, а другой массив имел размер больше 1, первый массив ведет себя так, как если бы он был скопирован вдоль этого измерения.

В книге `Python Data Science Handbook: Essential Tools for Working with Data` под авторством `Jake VanderPlas` трансляция массивов описывается тремя правилами:
1. Если размерность двух массивов отличается, форма массива с меньшей размерностью дополняется единицами с ведущей (левой) стороны.
2. Если форма двух массивов не совпадает в каком-то измерении, массив с формой, равной 1 в данном измерении, растягивается вплоть до соответствия форме другого массива.
3. Если в каком-либо измерении размеры массивов различаются и ни один не равен 1, генерируется ошибка.

Если это объяснение непонятно, попробуйте прочитать объяснение из [документации](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) или этого [объяснения](http: // wiki.scipy.org/EricsBroadcastingDoc).

Вот некоторые примеры использования трансляции:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Трансляция обычно делает ваш код более кратким и быстрым, поэтому вы должны стремиться использовать его там, где это возможно.

##### Трансляция. Пример 1.

Рассмотрим сложение двумерного массива с одномерным:
``` 
M = np.ones((2, 3))
a = np.arange(3)
```
Рассмотрим эту операцию подробнее. Формы массивов следующие:
```
M.shape = (2, 3)
a.shape = (3,)
```
По правилу 1, поскольку размерность массива a меньше, мы дополняем его из-
мерениями слева:
```
M.shape -> (2, 3)
a.shape -> (1, 3)
```
По правилу 2 мы видим, что первое измерение массивов различается, так что мы 
растягиваем его вплоть до совпадения:
```
M.shape -> (2, 3)
a.shape -> (2, 3)
```
Формы совпадают, и мы видим, что итоговая форма будет (2, 3). Проверим:

In [ ]:
M = np.ones((2, 3))
a = np.arange(3)
M+a

##### Транслирование. Пример 2
Рассмотрим пример, в котором необходимо транслировать оба массива:
```
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
```
Начнем с записи формы наших массивов:
```
a.shape = (3, 1)
b.shape = (3,)
```
Правило 1 гласит, что мы должны дополнить форму массива b единицами:
```
a.shape -> (3, 1)
b.shape -> (1, 3)
```
Правило 2 говорит, что нужно увеличивать эти единицы вплоть до совпадения 
с размером другого массива:
```
a.shape -> (3, 3)
b.shape -> (3, 3)
```
Поскольку результаты совпадают, формы совместимы. Получаем:


In [ ]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a+b

##### Транслирование. Пример 3
Рассмотрим пример, в котором два массива несовместимы:
```
M = np.ones((3, 2))
a = np.arange(3)
```
Эта ситуация лишь немного отличается от примера 1: матрица M транспонирована. Какое же влияние это окажет на вычисления? Формы массивов следующие:
```
M.shape = (3, 2)
a.shape = (3,)
```
Правило 1 требует от нас дополнить форму массива a единицами:
```
M.shape -> (3, 2)
a.shape -> (1, 3)
```
Согласно правилу 2 первое измерение массива a растягивается, чтобы соответствовать таковому массива M:
```
M.shape -> (3, 2)
a.shape -> (3, 3)
```
Теперь вступает в действие правило 3 — итоговые формы не совпадают, так что массивы несовместимы, что мы и видим, попытавшись выполнить данную операцию:

In [ ]:
M = np.ones((3, 2))
a = np.arange(3)
M+a

Обратите внимание на имеющийся потенциальный источник ошибки: можно было бы сделать массивы a и M совместимыми, скажем путем дополнения формы a единицами справа, а не слева. Но правила транслирования работают не так! 
Если вам хочется применить правостороннее дополнение, можете сделать это явным образом, поменяв форму массива. Для этого воспользуемся ключевым словом `np.newaxis`:

In [ ]:
a[:, np.newaxis].shape

In [ ]:
M + a[:, np.newaxis]

Этом краткий обзор затронул многие важные вещи, которые вам нужно знать о numpy, но далеко не все. Смотрите [документацию по numpy](http://docs.scipy.org/doc/numpy/reference/), чтобы узнать больше о numpy.

##### <font color=red>Задание</font>
Возможна ли совместная трансляция массивов с формами:
1. (100,100,4) и (3) ?
2. (15,1,6,5) и (7,1,5) ?
3. (12,3,8) и (3,1) ?
4. (10,4,1,6) и (3,1,6) ?
5. (10,1) и (1,10,3) ?

Дать подробные ответы (аналогично примерам, приведенным выше) со ссылками на правила трансляции и сопроводить примерами с вычислениями и комментариями.

In [ ]:
# Выполнение задания.
np.random.seed(0)
# Нет
# (3,) -> (1, 1, 3) -> (100, 100, 3)
#                      (100, 100, 4)
# 3 != 4 -> нельзя
matrix = np.array(np.random.randint(100, size=(100, 100, 4)))
arr = np.arange(3)
print(matrix + arr)

# Да
# (7, 1, 5) -> (1, 7, 1, 5)  -> (15, 7, 6, 5)
#              (15, 1, 6, 5) -> (15, 7, 6, 5)
matrix1 = np.array(np.random.randint(100, size=(15, 1, 6, 5)))
matrix2 = np.array(np.random.randint(100, size=(7, 1, 5)))
print(matrix1 + matrix2)

# Да
# (3, 1) -> (1, 3, 1) -> (12, 3, 18)
#                        (12, 3, 18)
matrix1 = np.array(np.random.randint(100, size=(12, 3, 18)))
matrix2 = np.array(np.random.randint(100, size=(3, 1)))
print(matrix1 + matrix2)

# Нет
# (3, 1, 6) -> (1, 3, 1, 6) -> (10, 3, 1, 6)
#                              (10, 4, 1, 6)
# 3 != 4 -> нельзя
matrix1 = np.array(np.random.randint(100, size=(10, 4, 1, 6)))
matrix2 = np.array(np.random.randint(100, size=(3, 1, 6)))
print(matrix1 + matrix2)

# Да
# (3, 1) -> (1, 3, 1) -> (12, 3, 18)
#                        (12, 3, 18)
matrix1 = np.array(np.random.randint(100, size=(12, 3, 18)))
matrix2 = np.array(np.random.randint(100, size=(3, 1)))
print(matrix1 + matrix2)

#### Универсальные функции

Функции, поддерживающие трансляцию, известны как **универсальные функции**. Вы можете найти список всех универсальных функций в [документации](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

**<font color=orange>Вычисления с применением векторизации посредством универсальных функций практически всегда более эффективны, чем их эквиваленты, реализованные с помощью циклов Python, особенно при росте размера массивов.</font>**

* Арифметические функции над массивами

In [ ]:
 x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # деление с округлением в меньшую сторону
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

Дополнительно эти операции можно комбинировать любыми способами с соблюдением стандартного приоритета выполнения операций:


In [ ]:
-(0.5*x + 1) ** 2

* Абсолютное значение.

Используется универсальная функция библиотеки NumPy — `np.absolute`, доступная также под псевдонимом `np.abs`:

In [ ]:
np.absolute(x)

In [ ]:
np.abs(x)

In [ ]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

#### Указание массива для вывода результата
При больших вычислениях удобно задать массив, в котором будет сохранен результат вычисления. Вместо того чтобы создавать временный массив, можно воспользоваться этой возможностью для записи результатов вычислений непосредственно 
в нужное вам место памяти. Сделать это для любой универсальной функции можно с помощью аргумента out:

In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

Эту возможность можно использовать даже вместе с представлениями массивов. Например, можно записать результаты вычислений в каждый второй элемент заданного массива:

In [ ]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

Если бы мы вместо этого написали `y[::2] = 2 ** x`, был бы создан временный массив для хранения результатов операции `2 ** x` с последующим копированием этих значений в массив y. Для столь незначительных объемов вычислений особой разницы нет, но для очень больших массивов экономия памяти за счет аккуратного использования аргумента out может оказаться значительной.

##### <font color=red>Задание</font>
Создать класс наследник от класса учета рейтинга студентов (**StudentsRaiting**) и расширить его методами рассчета статистики по предметам (средний балл, максимальный балл, минимальный балл). Для этого нужно преобразовать данные об оценках из словаря в массив и использовать функции библиотеки Numpy.

Примечание: Использовать универсальные функции для работы с массивами numpy.

In [ ]:
# Выполнение задания
import numpy as np

class ImprovedStudentsRating(StudentsRating):

    def __init__(self, studentsToGrade):
        super(ImprovedStudentsRating, self).__init__(studentsToGrade)
        self.Grades = np.array(list(studentsToGrade.values()))

    def average(self):
        return np.mean(self.Grades, axis=0)

    def min(self):
        return np.min(self.Grades, axis=0)

    def max(self):
        return np.max(self.Grades, axis=0)


students = {"Иванов Петр Николавич": (3, 3, 5, 4), "Петров Иван Константинович": (5, 4, 5, 4), "Сидоров Емельян Егорович": (4, 3, 4, 5)}
isr = ImprovedStudentsRating(students)
print(isr)

print(isr.average())
print(isr.min())
print(isr.max())


##### <font color=red>Задание</font>
0. Создать функцию `Function1(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=1/(1+exp(-x)`. Создать функцию `Function2(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=max(0,x)`.
1. Написать функцию `LinearTransform(M,x,b)`, где `M` - матрица, `x` - вектор, `b` - число. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=M*x+b`, здесь под операцией `*` понимается операция скалярного произведения (dot product) матрицы на вектор.
2. Написать функцию `Transform(M1,M2,x,b1,b2)`, где `M1`,`M2` - матрицы, `x` - вектор, `b1`,`b2` - числа. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=Function2(LinearTransform(M2,x2,b2))`, а `x2=Function1(LinearTransform(M1,x,b1))`.
3. Задать матрицы M1,M2 размером MxN, вектор размером N, и числа b1,b2 и выполнить вычисления `Transform(M1,M2,x,b1,b2)`, производя замеры времени выполнения функции. **Значения M и N нужно узнать у преподавателя.** 

Все функции задания нужно реализовать в двух вариантах: 
* с использованием универсальных векторизованных операций;
* с использованием циклов для вычислений.

Сравнить время выполнения для обеих реализаций и сделать выводы.

In [ ]:
#Выполнение задания
import numpy as np
import math as m
import time as tm


def Function1(vector):
    return 1 / (1 + np.exp(-vector))


def Function1S(vector):
    return np.array([1 / (1 + m.exp(-x)) for x in vector])


def Function2(vector):
    return np.maximum(vector, np.zeros_like(x))


def Function2S(vector):
    return np.array([max(0, x) for x in vector])


def LinearTransform(M, x, b):
    return np.dot(M, x) + b


def LinearTransformS(M, x, b):
    return np.array([sum([j * y for j, y in zip(i, x)]) + b for i in M])


def Transform(M1, M2, x, b1, b2):
    # Здесь M2 нужно транспонировать, иначе проблемы с размерностью
    return Function2(LinearTransform(M2.T, Function1(LinearTransform(M1, x, b1)), b2))


def TransformS(M1, M2, x, b1, b2):
    # Здесь M2 нужно транспонировать, иначе проблемы с размерностью
    return Function2S(LinearTransformS(M2.T, Function1S(LinearTransformS(M1, x, b1)), b2))


np.random.seed(0)
M1 = np.random.randint(0, 5, size=[10000, 10000])
M2 = np.random.randint(0, 5, size=[10000, 10000])
x = np.array(np.random.randint(0, 5, size=10000))
b1 = 1
b2 = 2


print("Function1, numpy: ")
start_time = tm.time()
Function1(x)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit Function1(x)

print("Function1S, vanilla python: ")
start_time = tm.time()
Function1S(x)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit Function1S(x)


print("Function2, numpy: ")
start_time = tm.time()
Function2(x)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit Function2(x)

print("Function2S, vanilla python: ")
start_time = tm.time()
Function2S(x)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit Function2S(x)


print("LinearTransform, numpy: ")
start_time = tm.time()
LinearTransform(M1, x, b1)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit LinearTransform(M1, x, b1)

print("LinearTransformS, vanilla python: ")
start_time = tm.time()
LinearTransformS(M1, x, b1)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit LinearTransformS(M1, x, b1)


M1 = np.random.randint(0, 3, size=[10000, 7000])
M2 = np.random.randint(0, 5, size=[10000, 7000])
x = np.array(np.random.randint(0, 5, size=7000))


print("Transform, numpy: ")
start_time = tm.time()
Transform(M1, M2, x, b1, b2)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit Transform(M1, M2, x, b1, b2)

print("TransformS, vanilla python: ")
start_time = tm.time()
TransformS(M1, M2, x, b1, b2)
end_time = tm.time()
print("--- %s seconds ---" % (end_time - start_time))
%timeit TransformS(M1, M2, x, b1, b2)


### Matplotlib

Matplotlib - это графическая библиотека. В этом разделе дается краткое введение в модуль matplotlib.pyplot, который предоставляет систему построения графиков, аналогичную системе MATLAB.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import numpy as np

Запустив эту специальную команду iPython,графики будут встроены в документ:

In [ ]:
%matplotlib inline

#### Графики

Самая важная функция в `matplotlib` - это `plot`, которая позволяет вам строить графики для двумерных данные. Вот простой пример:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

Немного усложнив пример мы можем легко построить несколько строк одновременно и добавить метки заголовка, легенды и оси:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

#### <font color=red>Задание</font>
Построить графики функций: $y=\sin(x)$,$y=\cos(x)$, $y=tg(x)$, $y=ctg(x)$. 
Требования к графикам:
- все графики в одной системе координат
- значения по оси x должны меняться от $-\pi$ до $\pi$.
- подписи по осям координат 
- название графика
- координатная сетка
- легенда.

In [ ]:
# Выполнение задания.
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

x = np.arange(-np.pi, np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
y_tan = np.tan(x)
y_cotan = 1 / y_tan

plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.plot(x, y_tan)
plt.plot(x, y_cotan)
plt.grid(color='b', linestyle='-.', linewidth=0.25)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine, Cosine, Tangent and Cotangent')
plt.legend(['Sine', 'Cosine', 'Tangent', 'Cotangent'])

# Из-за того, что тангенс и котангенс имеют точки разрыва 2 порядка в -pi/2, pi/2 и -pi, 0, pi соответственно,
# график не репрезентативен, поэтому можно взять другой отрезок x


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

# График тангенса, -5 * pi / 12 <= x <= 5 * pi / 12

x_tan = np.arange(-5*np.pi/12, 5*np.pi/12, 0.1)
y_tan = np.tan(x_tan)

plt.plot(x_tan, y_tan)
plt.grid(color='b', linestyle='-.', linewidth=0.25)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Tangent')
plt.legend(['Tangent'])


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

# График котангенса, , pi / 12 <= x <= 11 * pi / 12

x_cotan = np.arange(np.pi/12, 11*np.pi/12, 0.1)
y_cotan = 1 / np.tan(x_cotan)

plt.plot(x_cotan, y_cotan)
plt.grid(color='b', linestyle='-.', linewidth=0.25)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Cotangent')
plt.legend(['Cotangent'])


#### Подграфики 

Вы можете изображать разные графики на том же рисунке, используя функцию `subplot`. /пример:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
    plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

Вы можете больше узнать о функции `subplot` в [документации](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

#### <font color=red>Задание</font>
Построить графики функций: $y=2\cdot x^2$, $y=-2\cdot x^2$, $x=2\cdot y^2$, $x=-2\cdot y^2$
Требования к графикам:
- каждый график построить в своей системе координат, разделив лист на 4 равные части 2х2.
- значения по осям x и y должны меняться от 5 до 5.
- подписи по осям координат 
- названия графиков
- координатная сетка.

In [ ]:
# Выполнение задания.
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)

y_1 = 2 * x ** 2
plt.subplot(2, 2, 1)
plt.plot(x, y_1)
plt.title('y = 2 * x ** 2')
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.grid(color='b', linestyle='-.', linewidth=0.25)

y_2 = -2 * x ** 2
plt.subplot(2, 2, 2)
plt.plot(x, y_2)
plt.title('y = -2 * x ** 2')
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.grid(color='b', linestyle='-.', linewidth=0.25)

x_1 = 2 * y ** 2
plt.subplot(2, 2, 3)
plt.plot(y, x_1)
plt.title('x = 2 * y ** 2')
plt.xlabel('y axis label')
plt.ylabel('x axis label')
plt.grid(color='b', linestyle='-.', linewidth=0.25)

x_2 = -2 * y ** 2
plt.subplot(2, 2, 4)
plt.plot(y, x_2)
plt.title('x = -2 * y ** 2')
plt.xlabel('y axis label')
plt.ylabel('x axis label')
plt.grid(color='b', linestyle='-.', linewidth=0.25)


#### Гистограммы
Для построения гистограмм в IPython можно использовать разные способы. Расчет гистограммы оптимизированный для массивов с большим количеством элементов выполняется при помощи функции `np.histogram` из библиотеки NumPy. Например:

In [ ]:
np.histogram([1, 2, 1, 1, 2, 0], bins=[0, 1, 2, 3])

Для вычисления относительных значений в гистограмме можно использовать параметр `density=True`

In [ ]:
np.histogram([1, 2, 1, 1, 2, 0], bins=[0, 1, 2, 3],density=True)

Для построения графика гистограммы в Matplotlib есть соответствующая, функция, которая основана на функции библиотеки NumPy: 

In [ ]:
plt.hist([1, 2, 1, 1, 2, 0], bins=[0, 1, 2, 3])

In [ ]:
plt.hist([1, 2, 1, 1, 2, 0], bins=[0, 1, 2, 3],density=True)

#### <font color=red>Задание</font>
Сгенерировать 1000 случайных значений выбранного распределения (вид уточнить у преподавателя) и построить гистограмму частот и гистограмму относительных частот. 
Требования к графикам:
- графики расположить горизонтально
- подписи по осям координат 
- названия графиков.

In [ ]:
# Выполнение задания.
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

np.random.seed(0)
# В качестве распределения возмем нормальное стандартное распределение
mu, sigma = 0, 1.0
h = np.random.normal(mu, sigma, 1000)
# Формируем bins в соответствии с правилом трех сигм
bins = np.arange(-3 * sigma, 3 * sigma, 0.05)

plt.subplot(2, 1, 1)
plt.hist(h, bins=bins, density=False)
plt.title('Гистограмма частот норм. стандартного распр.')
plt.xlabel('Значения')
plt.ylabel('Частота')

plt.subplot(2, 1, 2)
plt.hist(h, bins=bins, density=True)
plt.title('Гистограмма отн. частот норм. стандартного распр.')
plt.xlabel('Значения')
plt.ylabel('Частота')


#### Диаграммы рассеивания (Scatter plot)
Диаграмма рассеивания представляет собой график, в котором точки не соединяются отрезками линий, а представлены по отдельности точками, кругами или другими фигурами на графике.

Пример построения диаграммы рассеивания с использованием функции `plot` библиотеки `matplotlib`:

In [ ]:
x = np.linspace(0, 10, 30)
y = np.sin(x)
plt.plot(x, y, 'o', color='black');

Используя функцию `plot` можно совместить диаграмму рассеивания и линейный график:

In [ ]:
 plt.plot(x, y, '-ok');  # линия (-), маркер круга (o), черный цвет (k)

Также диаграммы рассеивания могут быть построены с использованием функции `scatter` библиотеки `matplotlib`:

In [ ]:
 plt.scatter(x, y, marker='o');

Основное различие между функциями `plt.scatter` и `plt.plot` состоит в том, что с помощью первой можно создавать диаграммы рассеяния с индивидуально задаваемыми (или выбираемыми в соответствии с данными) свойствами каждой точки (размер, цвет заливки, цвет рамки и т. д.).

Продемонстрируем это, создав случайную диаграмму рассеяния с точками различных цветов и размеров. Чтобы лучше видеть перекрывающиеся результаты, воспользуемся ключевым словом `alpha` для настройки уровня прозрачности:

In [ ]:
rng = np.random.RandomState(0)
x = rng.randn(100)
y = rng.randn(100)
colors = rng.rand(100)
sizes = 1000 * rng.rand(100)
plt.scatter(x, y, c=colors, s=sizes, alpha=0.3)
plt.colorbar();  # Отображаем цветовую шкалу

#### <font color=red>Задание</font>
Повторить крайний пример, изменив вид распределений, используемый для генерации массивов x и y (вид распределений уточнить у преподавателя).

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# Возьмем распределение Лапласа

rng = np.random.RandomState(0)
x = np.random.laplace(size=100)
y = np.random.laplace(size=100)
colors = rng.rand(100)
sizes = 1000 * rng.rand(100)
plt.scatter(x, y, c=colors, s=sizes, alpha=0.3)
plt.colorbar()  # Отображаем цветовую шкалу


### SciPy

SciPy основывается на массивах и операциях над массивами библиотеки NumPy и предоставляет большое количество функций, которые работают с массивами Numpy и полезны для различных научных и инженерных приложений.

Лучший способ познакомиться с SciPy - изучить [документацию](http://docs.scipy.org/doc/scipy/reference/index.html). Мы выделим некоторые части SciPy, которые могут оказаться полезными для изучения материалов курса.

#### Работа с изображениями

SciPy предоставляет некоторые базовые функции для работы с изображениями. Например, функции для чтения изображений с диска в массивы numpy, для сохранения массивов numpy на диск как изображений и для изменения изображений. Вот простой пример, демонстрирующий эти функции:

In [ ]:
#from imageio import imread, imsave, imresize
import numpy as np
from imageio import imread, imsave
from PIL import Image

# Читаем изображение из файла JPEG в массив numpy.
#im = Image.open('cat.jpg', mode='r')
img = imread('cat.jpg')

print(img.dtype, img.shape)  # "uint8 (400, 248, 3)"

# Мы можем изменить оттенок изображения, масштабируя каждый из цветовых каналов
# с помощью константы. Изображение имеет форму (400, 248, 3);
# мы умножаем его на массив [1, 0.95, 0.9] формы (3);
# Трансляция массивов numpy привеодит к тому, что красный канал не изменит значение,
# а зеленый и синий каналы будут умножены на 0,95 и 0,9 соответственно.
img_tinted = np.uint8(img * [1, 0.95, 0.9])

img_tinted = Image.fromarray(obj=img_tinted)

# Изменим размер изображения на 300x300.
#img_tinted = imresize(img_tinted, (300, 300))
img_tinted = img_tinted.resize((300, 300))

# Сохраним на диск обработанное изображение.
imsave('cat_tinted.jpg', img_tinted)

Вы можете использовать функцию `imshow` из `matplotlib` для отображения изображений. Вот пример:

In [ ]:
img = imread('cat.jpg')
img_tinted = img * [1, 0, 0.9]

fig=plt.figure(figsize=(16, 8)) # Установим размер фигуры для отрисовки графиков.

# Отобразим исходное изображение
plt.subplot(1, 2, 1)
plt.imshow(img)

# Отобразим измененное изображение
plt.subplot(1, 2, 2)

# Небольшая проблема с imshow заключается в том, что функция может дать странные результаты
# если данные не являются uint8. Чтобы избежать этого, нужно привести изображение к типу 
# uint8 перед его отображением.
plt.imshow(np.uint8(img_tinted))
plt.show()

#### <font color=red>Задание</font>
1. Выбрать произвольное цветное изображение и загрузить в среду IPython.
2. Построить гистограммы яркостей для всех трех каналов.
3. Используя матричные операции обнулить яркости синего и зеленого каналов в изображении и отобразить его. 
4. Используя матричные операции обнулить яркости красного канала в изображении и отобразить его.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

img = imread('Lenna.png')

r = img[..., 0]
g = img[..., 1]
b = img[..., 2]

plt.subplot(311)
plt.hist(r, bins=np.arange(256))
plt.title('Red')
plt.xlabel('Значения')
plt.ylabel('Частота')

plt.subplot(312)
plt.hist(g, bins=np.arange(256))
plt.title('Green')
plt.xlabel('Значения')
plt.ylabel('Частота')

plt.subplot(313)
plt.hist(b, bins=np.arange(256))
plt.title('Blue')
plt.xlabel('Значения')
plt.ylabel('Частота')


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

img1 = imread('Lenna.png')
img2 = imread('Lenna.png')

img1[..., 0] *= 0 # Red
img2[..., 1] *= 0 # Green
img2[..., 2] *= 0 # Blue

fig = plt.figure(figsize=(16, 8))

plt.subplot(1, 2, 1)
plt.imshow(np.uint8(img1))

plt.subplot(1, 2, 2)
plt.imshow(np.uint8(img2))
